version: '3'

services:
    api:
        build: ./server
        ports:
            - '3007:3007'
        container_name: mm-server

    client:
        build: ./client
        ports:
            - '3000:80'
        depends_on:
            - api
        container_name: mm-client
