const users = [
    {
        _id: 'mamd0J1jtBP7vfwrOKDmB6f9Gcs1',
        contacts: [
            'xApfstyhFpTxakKLdluSsQgvjNK2',
            'NfstSlljE4X0QkL4A1Pnjt3vc1K3',
            'Ccn0NCg3uwMGjli3M5Z6CqSE1kB3',
            'n55eQxlp3Rg7nDdp3jjpcPSLk7e2',
            '7wvUMw5tjbc0NE1C3tnB9JrWXkx2',
        ],
        firstName: 'Buddy',
        lastName: 'Jones',
        email: 'test1@gmail.com',
        __v: 0,
    },
    {
        _id: 'xApfstyhFpTxakKLdluSsQgvjNK2',
        contacts: [
            'mamd0J1jtBP7vfwrOKDmB6f9Gcs1',
            'gGqRFYLqS0eMdITccd2M4fzAmYl1',
            'DN1ufRvbNrbfNN9fAyk1id4w33j1',
            'Ccn0NCg3uwMGjli3M5Z6CqSE1kB3',
            '7wvUMw5tjbc0NE1C3tnB9JrWXkx2',
        ],
        firstName: 'John',
        lastName: 'Myers',
        email: 'test2@gmail.com',
        __v: 0,
    },
    {
        _id: 'JTiGfOYaAgS0Q9GpaeW6Hl9HIk42',
        contacts: [
            'NfstSlljE4X0QkL4A1Pnjt3vc1K3',
            'DN1ufRvbNrbfNN9fAyk1id4w33j1',
            'Ccn0NCg3uwMGjli3M5Z6CqSE1kB3',
            '7wvUMw5tjbc0NE1C3tnB9JrWXkx2',
        ],
        firstName: 'Bill',
        lastName: 'Moss',
        email: 'test3@gmail.com',
        __v: 0,
    },
    {
        _id: 'gGqRFYLqS0eMdITccd2M4fzAmYl1',
        contacts: [
            'xApfstyhFpTxakKLdluSsQgvjNK2',
            'Ccn0NCg3uwMGjli3M5Z6CqSE1kB3',
            'n55eQxlp3Rg7nDdp3jjpcPSLk7e2',
        ],
        firstName: 'Matt',
        lastName: 'Field',
        email: 'test4@gmail.com',
        __v: 0,
    },
    {
        _id: 'NfstSlljE4X0QkL4A1Pnjt3vc1K3',
        contacts: [
            'mamd0J1jtBP7vfwrOKDmB6f9Gcs1',
            'JTiGfOYaAgS0Q9GpaeW6Hl9HIk42',
        ],
        firstName: 'Jane',
        lastName: 'Star',
        email: 'test5@gmail.com',
        __v: 0,
    },
    {
        _id: 'DN1ufRvbNrbfNN9fAyk1id4w33j1',
        contacts: [
            'xApfstyhFpTxakKLdluSsQgvjNK2',
            'JTiGfOYaAgS0Q9GpaeW6Hl9HIk42',
        ],
        firstName: 'Andy',
        lastName: 'Friend',
        email: 'test6@gmail.com',
        __v: 0,
    },
    {
        _id: 'Ccn0NCg3uwMGjli3M5Z6CqSE1kB3',
        contacts: [
            'mamd0J1jtBP7vfwrOKDmB6f9Gcs1',
            'JTiGfOYaAgS0Q9GpaeW6Hl9HIk42',
            'xApfstyhFpTxakKLdluSsQgvjNK2',
            'gGqRFYLqS0eMdITccd2M4fzAmYl1',
        ],
        firstName: 'Daniel',
        lastName: 'Moore',
        email: 'test7@gmail.com',
        __v: 0,
    },
    {
        _id: 'n55eQxlp3Rg7nDdp3jjpcPSLk7e2',
        contacts: [
            'mamd0J1jtBP7vfwrOKDmB6f9Gcs1',
            'gGqRFYLqS0eMdITccd2M4fzAmYl1',
        ],
        firstName: 'Jacky',
        lastName: 'Daun',
        email: 'test8@gmail.com',
        __v: 0,
    },
    {
        _id: 'vsn2FcVctWW5Dp6xQaDTZTG5Ro23',
        contacts: [],
        firstName: 'James',
        lastName: 'Quincy',
        email: 'test9@gmail.com',
        __v: 0,
    },
    {
        _id: '7wvUMw5tjbc0NE1C3tnB9JrWXkx2',
        contacts: [
            'JTiGfOYaAgS0Q9GpaeW6Hl9HIk42',
            'mamd0J1jtBP7vfwrOKDmB6f9Gcs1',
            'xApfstyhFpTxakKLdluSsQgvjNK2',
        ],
        firstName: 'Mark',
        lastName: 'Turner',
        email: 'test10@gmail.com',
        __v: 0,
    },
];
